#----------CONFIGS-----------------

[[mgr.prepend_keymap]]
on = [ "g", "p"]
run = "cd ~/Projects"
desc = "Go to project directory"

[[mgr.prepend_keymap]]
on = [ "g", "r"]
run = "cd ~/Releases"
desc = "Go to releases directory"

[[mgr.prepend_keymap]]
on = [ "g", "m"]
run = "cd /run/media/kukaracka/"
desc = "Go to attached devices"

[[mgr.prepend_keymap]]
on = [ "g", "c"]
run = "cd ~/.dotfiles/all-configs/.config"
desc = "Go to dotfiles directory"

#-----------DIRECTORIES-------------

[[mgr.prepend_keymap]]
on = [ "g", "h", "w" ]
run = "cd ~/Downloads"
desc = "cd ~/Downloads"

[[mgr.prepend_keymap]]
on = [ "g", "h", "d" ]
run = "cd ~/Documents"
desc = "cd ~/Documents"

[[mgr.prepend_keymap]]
on = [ "g", "h", "v" ]
run = "cd ~/Videos"
desc = "cd ~/Videos"

[[mgr.prepend_keymap]]
on = [ "g", "h", "c" ]
run = "cd ~/.config"
desc = "cd ~/.config"

[[mgr.prepend_keymap]]
on = [ "g", "h", "t"]
run = "cd ~/.local/share/Trash/files"
desc = "cd ~/.local/share/Trash/file"

#-------------Plugins-------------
#
[[mgr.prepend_keymap]]
on = ["C"]
run = "plugin ouch"
desc = "Compress with ouch"

[[mgr.prepend_keymap]]
on   = ["D"]
run  = "shell 'ouch d \"$@\"' --confirm"
desc = "Decompress with ouch"

[[mgr.prepend_keymap]]
on   = [ "c", "d" ]
run  = 'exec /usr/bin/ripdrag --no-click --and-exit --icon-size 64 --target --all "$@"'
desc = "Drag out files"
