#----------CONFIGS-----------------

# [[mgr.prepend_keymap]]
# on = [ "g", "c", "y" ]
# run = "cd ~/.config/yazi"
# desc = "cd ~/.config/yazi"
#
# [[mgr.prepend_keymap]]
# on = [ "g", "c", "h" ]
# run = "cd ~/.config/hypr"
# desc = "cd ~/.config/hypr"
#
# [[mgr.prepend_keymap]]
# on = [ "g", "c", "f"]
# run = "cd ~/.config/fish"
# desc = "cd ~/.config/fish"
#
# [[mgr.prepend_keymap]]
# on = [ "g", "c", "k"]
# run = "cd /etc/keyd"
# desc = "cd /etc/keyd"

[[mgr.prepend_keymap]]
on = [ "g", "p"]
run = "cd ~/Projects"
desc = "Go to project directory"

[[mgr.prepend_keymap]]
on = [ "g", "m"]
run = "cd /run/media/kukaracka/"
desc = "Go to attached devices"

[[mgr.prepend_keymap]]
on = [ "g", "c"]
run = "cd ~/.dotfiles/all-configs/.config"
desc = "Go to dotfiles directory"

#-----------DIRECTORIES-------------

[[mgr.prepend_keymap]]
on = [ "g", "w" ]
run = "cd ~/Downloads"
desc = "cd ~/Downloads"

[[mgr.prepend_keymap]]
on = [ "g", "d", "d" ]
run = "cd ~/Documents"
desc = "cd ~/Documents"

[[mgr.prepend_keymap]]
on = [ "g", "r" ]
run = "cd ~/Pictures"
desc = "cd ~/Pictures"

[[mgr.prepend_keymap]]
on = [ "g", "v" ]
run = "cd ~/Videos"
desc = "cd ~/Videos"

[[mgr.prepend_keymap]]
on = [ "g", "d", "c" ]
run = "cd ~/.config"
desc = "cd ~/.config"

[[mgr.prepend_keymap]]
on = [ "g", "t" ]
run = "cd ~/Torrents/"
desc = "cd ~/Torrents/"

[[mgr.prepend_keymap]]
on = [ "g", "d", "t"]
run = "cd ~/.local/share/Trash/files"
desc = "cd ~/.local/share/Trash/file"

#-------------Plugins-------------
[[mgr.prepend_keymap]]
on = ["C"]
run = "plugin ouch"
desc = "Compress with ouch"
