[mgr]
ratio          = [ 20, 50, 30 ] # Ширина колонок: дерево, список, превью
sort_by        = "alphabetical"
sort_sensitive = false
sort_reverse   = false
sort_dir_first = true
show_hidden    = true  # Всегда показывать скрытые файлы
show_symlink   = true
linemode = "size"

[preview]
tab_size        = 2
max_width       = 1000
max_height      = 1000
cache_dir       = ""

[[plugin.prepend_previewers]]
mime = "application/{*zip,tar,bzip2,7z*,rar,xz,zstd,java-archive}"
run  = "ouch"
 
# [plugin]
# prepend_previewers = [
# 	# Change the top-level archive icon
# 	{ ..., run = "ouch --archive-icon='🗄️ '" },
# 	# Or remove it by setting it to ''
# 	{ ..., run = "ouch --archive-icon=''" },
#
# 	# Enable file icons
# 	{ ..., run = "ouch --show-file-icons" },
#
# 	# Disable tree view
# 	{ ..., run = "ouch --list-view" },
#
# 	# These can be combined
# 	{ ..., run = "ouch --archive-icon='🗄️ ' --show-file-icons --list-view" },
# ]


[opener]
# Чем открывать файлы (настрой под свой софт)
edit = [
    { run = 'nvim "$@"', block = true, desc = "NeoVim" },
]
play_alt = [
    { run = 'mpv "$@"', orphan = true, desc = "MPV" },
]

copy = [

    { run = 'wl-copy < "$@"', orphan = true, desc = "Clipboard" },
]

play = [
    { run = 'vlc "$@"', orphan = true, desc = "VLC" },
]

open_img = [
    { run = 'gwenview "$@"', orphan = true, desc = "VLC" },
]
[open]
rules = [
	# Folder
	{ url = "*/", use = [ "edit", "open", "reveal", "copy"] },
	# Text
	{ mime = "text/*", use = [ "edit", "reveal", "copy" ] },
	# Image
	{ mime = "image/*", use = ["open_img" , "open", "reveal" , "copy"] },
	# Media
	{ mime = "{audio,video}/*", use = [ "play", "play_alt", "reveal" , "copy"] },
	# Archive
	{ mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", use = [ "extract", "reveal" ] },
	# JSON
	{ mime = "application/{json,ndjson}", use = [ "edit", "reveal" , "copy"] },
	{ mime = "*/javascript", use = [ "edit", "reveal" , "copy"] },
	# Empty file
	{ mime = "inode/empty", use = [ "edit", "reveal" , "copy"] },
	# Virtual file system
	{ mime = "vfs/{absent,stale}", use = "download", "copy" },
	# Fallback
	{ url = "*", use = [ "open", "reveal", "copy" ] },
  { url = "*.mkv", use = [ "play","play_alt",  "edit" ] },
]
