[mgr]
ratio          = [ 20, 50, 30 ] # Ширина колонок: дерево, список, превью
sort_by        = "alphabetical"
sort_sensitive = false
sort_reverse   = false
sort_dir_first = true
show_hidden    = true  # Всегда показывать скрытые файлы
show_symlink   = true

[preview]
tab_size        = 2
max_width       = 1000
max_height      = 1000
cache_dir       = ""

[opener]
# Чем открывать файлы (настрой под свой софт)
edit = [
    { run = 'nvim "$@"', block = true, desc = "NeoVim" },
]
play = [
    { run = 'mpv "$@"', orphan = true, desc = "MPV" },
]

copy = [

    { run = 'wl-copy < "$@"', orphan = true, desc = "Clipboard" },
]

play_vlc = [
    { run = 'vlc "$@"', orphan = true, desc = "VLC" },
]

open_img = [
    { run = 'gwenview "$@"', orphan = true, desc = "VLC" },
]
[open]
rules = [
	# Folder
	{ url = "*/", use = [ "edit", "open", "reveal", "copy"] },
	# Text
	{ mime = "text/*", use = [ "edit", "reveal", "copy" ] },
	# Image
	{ mime = "image/*", use = ["open_img" , "open", "reveal" , "copy"] },
	# Media
	{ mime = "{audio,video}/*", use = [ "play", "play_vlc", "reveal" , "copy"] },
	# Archive
	{ mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", use = [ "extract", "reveal" ] },
	# JSON
	{ mime = "application/{json,ndjson}", use = [ "edit", "reveal" , "copy"] },
	{ mime = "*/javascript", use = [ "edit", "reveal" , "copy"] },
	# Empty file
	{ mime = "inode/empty", use = [ "edit", "reveal" , "copy"] },
	# Virtual file system
	{ mime = "vfs/{absent,stale}", use = "download", "copy" },
	# Fallback
	{ url = "*", use = [ "open", "reveal", "copy" ] },
]
