gui:
  theme:
    activeBorderColor:
      - "#889fc4"
      - bold
    inactiveBorderColor:
      - "#7f77bb"
    searchingActiveBorderColor:
      - "#a177bb"
      - bold
    optionsTextColor:
      - "#afb2b6"
    selectedLineBgColor:
      - "#262c36"
    inactiveViewSelectedLineBgColor:
      - bold
    cherryPickedCommitFgColor:
      - "#afb2b6"
    cherryPickedCommitBgColor:
      - "#a177bb"
    markedBaseCommitFgColor:
      - "#a177bb"
    markedBaseCommitBgColor:
      - "#fd4663"
    unstagedChangesColor:
      - "#fd4663"
    defaultFgColor:
      - "#f2f2f3"
git:
  # Настройка внешнего вида диффов (разницы в коде)
  diffRenderers:
    - colorArg: always
      # Если установлен delta (рекомендую), раскомментируй строку ниже:
      # pager: delta --dark --paging=never

      type: rawGit
os:
  # Редактор, который будет открываться по нажатию 'e'
  # Возможные пресеты: nvim, vim, code (VS Code), nano
  editPreset: "nvim"
# Пример кастомной команды: нажми 'C', чтобы быстро сделать commit с текстом "wip"
customCommands:
  - key: "C"
    command: 'git commit -m "wip"'
    context: "files"
    description: "быстрый commit (wip)"
  - key: "G"
    context: "commits"
    description: "Search commits by content"
    prompts:
      - type: "input"
        title: "Enter search string:"
        key: "SearchString"
    # command: 'git log -S "{{.Form.SearchString}}" -p' # Сама команда[citation:7][citation:8]
    command: 'git log --all -S "{{.Form.SearchString}}" --stat'
    output: "popup"
