gui:
  # Включает иконки (нужен шрифт Nerd Font, например JetBrainsMono Nerd Font)
  theme:
    activeBorderColor:
      - "#8b9ac1"
      - bold
    inactiveBorderColor:
      - "#8c81b1"
    searchingActiveBorderColor:
      - "#a283af"
      - bold
    optionsTextColor:
      - "#afb1b6"
    selectedLineBgColor:
      - "#262a36"
    inactiveViewSelectedLineBgColor:
      - bold
    cherryPickedCommitFgColor:
      - "#afb1b6"
    cherryPickedCommitBgColor:
      - "#a283af"
    markedBaseCommitFgColor:
      - "#a283af"
    markedBaseCommitBgColor:
      - "#fd4663"
    unstagedChangesColor:
      - "#fd4663"
    defaultFgColor:
      - "#f2f2f3"
  nerdFontsVersion: "3"
  # Отображает измененные файлы в виде дерева, а не плоским списком
  showFileTree: true
  # Сразу выходит в терминал при закрытии (без подтверждения "Press enter")
  returnImmediately: true
  # Закругленные границы окон (выглядит современнее)
  border: "rounded"
  # Тема (акцент на синий/голубой, можно настроить под себя)
git:
  # Настройка внешнего вида диффов (разницы в коде)
  diffRenderers:
    - colorArg: always
      # Если установлен delta (рекомендую), раскомментируй строку ниже:
      # pager: delta --dark --paging=never

      type: rawGit
os:
  # Редактор, который будет открываться по нажатию 'e'
  # Возможные пресеты: nvim, vim, code (VS Code), nano
  editPreset: "nvim"
# Пример кастомной команды: нажми 'C', чтобы быстро сделать commit с текстом "wip"
customCommands:
  - key: "C"
    command: 'git commit -m "wip"'
    context: "files"
    description: "быстрый commit (wip)"
