# [ids]
# 0001:0001:702b470b
#
# [main]
# capslock = overload(control, esc)
# rightalt = backspace
# # leftcontrol = overload(alt,macro(leftmeta+c))
# # leftshift = oneshot(shift)
#
# space = overloadt(layer_one, space, 200)
#
# a = overloadt(alt, a, 220)
# s = overloadt(meta, s, 200)
# d = overloadt(control, d, 200)
# f = overloadt(shift, f, 200)
#
# ; = overloadt(alt, ;, 200)
# l = overloadt(meta, l, 200)
# k = overloadt(control, k, 200)
# j = overloadt(shift, j, 200)
#
#
# d+k = enter
# f+j = macro(leftmeta+enter)
#
# leftalt = delete
#
# s+space=macro(leftmeta+space)
# leftshift = z
# z = x
# x = c
# c = v
# v = b
#
#
# e+r = (
# d+f = [
# x+c = {
#
# u+i = )
# j+k = ]
# m+, = }
#
# w+e = =
# z+x = +
#
# i+o = -
# ,+. = _
#
# space+f = macro(leftmeta+t)
#
# [layer_one]
#
# q=-
# w=7
# e=8
# r=9
# t=+
#
# a=p
# s=4
# d=5
# f=6
# g==
#
# leftshift = /
# z=1
# x=2
# c=3
# v=_
#
# leftalt = 0
#
# # y=macro(leftcontrol+o)
# # u=macro(leftcontrol+v)
# # i=macro(leftcontrol+x)
# # o=macro(leftcontrol+z)
# # p=macro(leftcontrol+b)
#
#
# u=home
# o=end
# y=pageup
# h=pagedown
# j = left
# k = down
# i = up
# l = right
#
# n=insert
#
#
#
# [layer_two]
# q = macro(leftmeta+1)
# w = macro(leftmeta+2)
# e = macro(leftmeta+3)
# r = macro(leftmeta+4)
# t = macro(leftmeta+5)
# y = macro(leftmeta+6)
# u = macro(leftmeta+7)
# i = macro(leftmeta+8)
# o = macro(leftmeta+9)
# p = macro(leftmeta+0)
# h = macro(leftmeta+m)
# l = macro(leftmeta+u)
# j = macro(leftmeta+y)
# k = macro(leftmeta+n)
#
# space = space
