[ids]
*

[main]
capslock = overload(control, esc)
rightalt = backspace
# leftcontrol = overload(alt,macro(leftmeta+c))
# leftshift = oneshot(shift)

space = overloadt(layer_one, space, 150)

a = overloadt(alt, a, 150)
s = overloadt(meta, s, 150)
d = overloadt(control, d, 150)
f = overloadt(shift, f, 150)

; = overloadt(alt, ;, 150)
l = overloadt(meta, l, 150)
k = overloadt(control, k, 150)
j = overloadt(shift, j, 150)


d+k = enter
f+j = macro(leftmeta+enter)

leftalt = delete

leftcontrol = macro(leftmeta+c)
# leftshift = enter
s+space=macro(leftmeta+space)
leftshift = z
z = x
x = c
c = v
v = b


e+r = (
d+f = [
x+c = {

u+i = ) 
j+k = ]
m+, = }

s+d = "
k+l = '

s+l = macro(leftmeta+z)

[layer_one]

q=-
w=7
e=8
r=9
t=+

a=p
s=4
d=5
f=6
g==

leftshift = /
z=1
x=2
c=3
v=_

leftalt = 0

y=macro(leftcontrol+o)
u=macro(leftcontrol+v)
i=macro(leftcontrol+x)
o=macro(leftcontrol+z)
p=macro(leftcontrol+b)


h=macro(leftshift+7)
j = left
k = down
l = up
; = right

n=insert
m=home
,=pageup
.=pagedown
/=end



[layer_two]
q = macro(leftmeta+1)
w = macro(leftmeta+2)
e = macro(leftmeta+3)
r = macro(leftmeta+4)
t = macro(leftmeta+5)
y = macro(leftmeta+6)
u = macro(leftmeta+7)
i = macro(leftmeta+8)
o = macro(leftmeta+9)
p = macro(leftmeta+0)
h = macro(leftmeta+m)
l = macro(leftmeta+u)
j = macro(leftmeta+y)
k = macro(leftmeta+n)

space = space
