unbind-key -a -T root

set -g pane-border-lines "double"

set -g base-index 1
setw -g pane-base-index 1
set -g renumber-windows on

setw -g mode-keys vi

set -g mouse on

set -s escape-time 0

set -g history-limit 2000

# bind -n M-k source-file ~/.config/tmux/tmux.conf \; display "Config reloaded!"
bind -n M-s choose-tree -s

# Перемещение между панелями (Alt + стрелки) без префикса
bind -n M-Left select-pane -L
bind -n M-Right select-pane -R
bind -n M-Up select-pane -U
bind -n M-Down select-pane -D


# Перемещенме между вкладками
bind -n M-1 select-window -t 1
bind -n M-2 select-window -t 2
bind -n M-3 select-window -t 3
bind -n M-4 select-window -t 4
bind -n M-5 select-window -t 5
bind -n M-6 select-window -t 6
bind -n M-7 select-window -t 7
bind -n M-8 select-window -t 8
bind -n M-9 select-window -t 9

# Измененме размера панелей
bind -n M-S-Left resize-pane -L 5
bind -n M-S-Right resize-pane -R 5
bind -n M-S-Up resize-pane -U 3
bind -n M-S-Down resize-pane -D 3

# Сплит экрана
bind -n M-h split-window -v
bind -n M-v split-window -h

# Работа с окнами и вкладками
bind -n M-Enter new-window
bind -n M-c kill-pane
# bind -n M-q kill-window
bind -n M-d detach
bind -n M-Q confirm-before -p "Kill entire session? (y/n)" kill-session
bind -n M-r command-prompt -I "#W" "rename-window '%%'"

# Вход в режим копирования
bind -n M-/ copy-mode

set -g default-shell /usr/bin/fish



set -g @plugin 'tmux-plugins/tpm'
#-------------------------------------
set -g @plugin 'tmux-plugins/tmux-urlview'
#-------------------------------------
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @resurrect-dir '~/.config/tmux/resurrect'
set -g @resurrect-processes 'bluetui impala superseedr pomo btop nvtop'
#-------------------------------------
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @continuum-restore 'on'
set -g @continuum-save-interval '15'
#-------------------------------------
run '~/.config/tmux/plugins/tpm/tpm'

# Make the status line pretty and add some modules
set -g status-right-length 100
set -g status-left-length 100


# ~/.tmux.conf

set -g @plugin 'tmux-plugins/tpm' # mandatory
set -g @plugin 'tmux-plugins/tmux-sensible' # optional recommended

set -g @plugin 'egel/tmux-gruvbox'
# set desired theme options...
set -g @tmux-gruvbox 'dark' # or 'dark256', 'light', 'light256'

